CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251211064731_Init', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251211100046_Second', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "DailyReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "Task" character varying(500) NOT NULL,
    "Note" character varying(2000) NOT NULL,
    "ReportedTo" character varying(256) NOT NULL,
    "ApplicationUserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DailyReports" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251211135902_manager user', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251212070108_adminmanagerpass', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215062339_FixDailyReportSchema', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DailyReports" ALTER COLUMN "Task" TYPE text;

ALTER TABLE "DailyReports" ADD "SubmittedByRole" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216073730_AddSubmittedByRoleToDailyReport', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DailyReports" ALTER COLUMN "Task" TYPE text;

ALTER TABLE "DailyReports" ALTER COLUMN "ReportedTo" TYPE text;

ALTER TABLE "DailyReports" ALTER COLUMN "Note" TYPE text;

ALTER TABLE "DailyReports" ADD "AdminComment" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216080833_AddAdminComment', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "PasswordResetCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "AspNetUsers" ADD "PasswordResetDate" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216103919_AddPasswordResetLimit', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DailyReports" RENAME COLUMN "AdminComment" TO "ReviewerComment";

ALTER TABLE "DailyReports" ALTER COLUMN "Task" TYPE character varying(300);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251217091654_InitialReportsSchema', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "MobileNumber" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251222052429_AddMobileNumberToUsers', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" RENAME COLUMN "FirstName" TO "Name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251222061706_RemoveFirstNameAddName', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "ManagerId" text;

CREATE INDEX "IX_AspNetUsers_ManagerId" ON "AspNetUsers" ("ManagerId");

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_AspNetUsers_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223065449_AddManagerUserRelation', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223084802_Teammembers', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "ParentUserId" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251226055524_AddParentUserHierarchy', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DailyReports" ALTER COLUMN "Date" TYPE date;

CREATE UNIQUE INDEX "IX_DailyReports_ApplicationUserId_Date" ON "DailyReports" ("ApplicationUserId", "Date");

ALTER TABLE "DailyReports" ADD CONSTRAINT "FK_DailyReports_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251226174717_save todayreports', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "AssignedTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text,
    "Priority" text NOT NULL,
    "AssignedById" text NOT NULL,
    "AssignedToId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AssignedTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedById" FOREIGN KEY ("AssignedById") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AssignedTasks_AssignedById" ON "AssignedTasks" ("AssignedById");

CREATE INDEX "IX_AssignedTasks_AssignedToId" ON "AssignedTasks" ("AssignedToId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260121080213_AddAssignedTasks', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AssignedTasks" ADD "Status" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260121093848_AddAssignedTasksstatus', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "EmailChangeCodeExpiry" timestamp with time zone;

ALTER TABLE "AspNetUsers" ADD "EmailChangeLoginCode" text;

ALTER TABLE "AspNetUsers" ADD "PendingEmail" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125173116_AddPendingAdminEmailChange', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260126125249_database add', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "TaskItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "AssignedToUserId" text NOT NULL,
    "CreatedByUserId" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskItems_AssignedToUserId" ON "TaskItems" ("AssignedToUserId");

CREATE INDEX "IX_TaskItems_CreatedByUserId" ON "TaskItems" ("CreatedByUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260202111435_AddTaskBoard', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "ColumnId" integer NOT NULL DEFAULT 0;

ALTER TABLE "TaskItems" ADD "TeamName" text NOT NULL DEFAULT '';

CREATE TABLE "TeamColumns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeamName" text NOT NULL,
    "ColumnName" text NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_TeamColumns" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_TaskItems_ColumnId" ON "TaskItems" ("ColumnId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_TeamColumns_ColumnId" FOREIGN KEY ("ColumnId") REFERENCES "TeamColumns" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260202112343_InitialTeamColumns', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "UserTeams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TeamName" text NOT NULL,
    CONSTRAINT "PK_UserTeams" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserTeams_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserTeams_UserId" ON "UserTeams" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260203050151_AddUserTeams', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "UpdatedAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260204125444_AddUpdatedAtToTaskItem', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "AssignedAt" timestamp with time zone;

ALTER TABLE "TaskItems" ADD "AssignedByUserId" text;

CREATE INDEX "IX_TaskItems_AssignedByUserId" ON "TaskItems" ("AssignedByUserId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "AspNetUsers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260205062811_AddTaskAssignmentTracking', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "Address" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260206122152_AddAddressToUsers', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "StoryId" integer;

ALTER TABLE "TaskItems" ADD "WorkItemId" text;

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedByUserId" text NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Epics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkItemId" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ProjectId" integer NOT NULL,
    "CreatedByUserId" text,
    CONSTRAINT "PK_Epics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Epics_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Epics_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Features" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkItemId" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "EpicId" integer NOT NULL,
    "CreatedByUserId" text,
    CONSTRAINT "PK_Features" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Features_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Features_Epics_EpicId" FOREIGN KEY ("EpicId") REFERENCES "Epics" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkItemId" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "FeatureId" integer NOT NULL,
    "CreatedByUserId" text,
    CONSTRAINT "PK_Stories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stories_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Stories_Features_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Features" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskItems_StoryId" ON "TaskItems" ("StoryId");

CREATE INDEX "IX_Epics_CreatedByUserId" ON "Epics" ("CreatedByUserId");

CREATE INDEX "IX_Epics_ProjectId" ON "Epics" ("ProjectId");

CREATE INDEX "IX_Features_CreatedByUserId" ON "Features" ("CreatedByUserId");

CREATE INDEX "IX_Features_EpicId" ON "Features" ("EpicId");

CREATE INDEX "IX_Projects_CreatedByUserId" ON "Projects" ("CreatedByUserId");

CREATE INDEX "IX_Stories_CreatedByUserId" ON "Stories" ("CreatedByUserId");

CREATE INDEX "IX_Stories_FeatureId" ON "Stories" ("FeatureId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_Stories_StoryId" FOREIGN KEY ("StoryId") REFERENCES "Stories" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260208102756_AddProjectHierarchy', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "ProjectId" integer;

CREATE INDEX "IX_TaskItems_ProjectId" ON "TaskItems" ("ProjectId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260208110200_AddProjectIdToTask', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "Teams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209074137_AddTeamsTable04', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "Priority" integer NOT NULL DEFAULT 0;

CREATE TABLE "TaskCustomFields" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FieldName" text NOT NULL,
    "FieldType" text NOT NULL,
    "IsRequired" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" text,
    CONSTRAINT "PK_TaskCustomFields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskCustomFields_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "TaskFieldValues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "FieldId" integer NOT NULL,
    "Value" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_TaskFieldValues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskFieldValues_TaskCustomFields_FieldId" FOREIGN KEY ("FieldId") REFERENCES "TaskCustomFields" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskFieldValues_TaskItems_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskCustomFields_CreatedByUserId" ON "TaskCustomFields" ("CreatedByUserId");

CREATE INDEX "IX_TaskFieldValues_FieldId" ON "TaskFieldValues" ("FieldId");

CREATE INDEX "IX_TaskFieldValues_TaskId" ON "TaskFieldValues" ("TaskId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209164121_AddTaskPriorityAndCustomFields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "CurrentColumnEntryAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

CREATE TABLE "TaskHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "ChangeType" integer NOT NULL,
    "FieldChanged" text,
    "OldValue" text,
    "NewValue" text,
    "FromColumnId" integer,
    "ToColumnId" integer,
    "TimeSpentInSeconds" integer,
    "ChangedByUserId" text NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "Details" text,
    CONSTRAINT "PK_TaskHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskHistories_AspNetUsers_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TaskHistories_TaskItems_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskHistories_TeamColumns_FromColumnId" FOREIGN KEY ("FromColumnId") REFERENCES "TeamColumns" ("Id"),
    CONSTRAINT "FK_TaskHistories_TeamColumns_ToColumnId" FOREIGN KEY ("ToColumnId") REFERENCES "TeamColumns" ("Id")
);

CREATE INDEX "IX_TaskHistories_ChangedByUserId" ON "TaskHistories" ("ChangedByUserId");

CREATE INDEX "IX_TaskHistories_FromColumnId" ON "TaskHistories" ("FromColumnId");

CREATE INDEX "IX_TaskHistories_TaskId_ChangedAt" ON "TaskHistories" ("TaskId", "ChangedAt");

CREATE INDEX "IX_TaskHistories_ToColumnId" ON "TaskHistories" ("ToColumnId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209172649_AddTaskHistoryTracking', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "CanAddUsers" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "CanDeleteUsers" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "CanEditUsers" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260211092612_AddUserPermissions', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" DROP COLUMN "CanAddUsers";

ALTER TABLE "AspNetUsers" DROP COLUMN "CanDeleteUsers";

ALTER TABLE "AspNetUsers" DROP COLUMN "CanEditUsers";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212062550_FixPendingChanges', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "EmailLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ToEmail" character varying(256) NOT NULL,
    "Subject" character varying(256) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ErrorMessage" character varying(2000),
    "SentAt" timestamp with time zone NOT NULL,
    "SentByUserId" character varying(450),
    "EmailType" character varying(50) NOT NULL,
    CONSTRAINT "PK_EmailLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailLogs_AspNetUsers_SentByUserId" FOREIGN KEY ("SentByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_EmailLogs_SentByUserId" ON "EmailLogs" ("SentByUserId");

CREATE INDEX "IX_EmailLogs_ToEmail_SentAt" ON "EmailLogs" ("ToEmail", "SentAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260213053748_AddEmailLogs', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "ArchivedAt" timestamp with time zone;

ALTER TABLE "TaskItems" ADD "CompletedAt" timestamp with time zone;

ALTER TABLE "TaskItems" ADD "CompletedByUserId" text;

ALTER TABLE "TaskItems" ADD "IsArchived" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "TaskItems" ADD "PreviousColumnId" integer;

ALTER TABLE "TaskItems" ADD "ReviewNote" text;

ALTER TABLE "TaskItems" ADD "ReviewStatus" integer NOT NULL DEFAULT 0;

ALTER TABLE "TaskItems" ADD "ReviewedAt" timestamp with time zone;

ALTER TABLE "TaskItems" ADD "ReviewedByUserId" text;

CREATE INDEX "IX_TaskItems_CompletedByUserId" ON "TaskItems" ("CompletedByUserId");

CREATE INDEX "IX_TaskItems_PreviousColumnId" ON "TaskItems" ("PreviousColumnId");

CREATE INDEX "IX_TaskItems_ReviewedByUserId" ON "TaskItems" ("ReviewedByUserId");

CREATE INDEX "IX_TaskItems_TeamName_IsArchived" ON "TaskItems" ("TeamName", "IsArchived");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_CompletedByUserId" FOREIGN KEY ("CompletedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_TeamColumns_PreviousColumnId" FOREIGN KEY ("PreviousColumnId") REFERENCES "TeamColumns" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260213153048_AddReviewWorkflow', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskHistories" DROP CONSTRAINT "FK_TaskHistories_AspNetUsers_ChangedByUserId";

ALTER TABLE "TaskHistories" ALTER COLUMN "ChangedByUserId" DROP NOT NULL;

ALTER TABLE "TaskHistories" ADD CONSTRAINT "FK_TaskHistories_AspNetUsers_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214045736_MakeChangedByUserIdNullable', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "BoardPermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TeamName" text NOT NULL,
    "CanAddColumn" boolean NOT NULL,
    "CanRenameColumn" boolean NOT NULL,
    "CanReorderColumns" boolean NOT NULL,
    "CanDeleteColumn" boolean NOT NULL,
    "CanEditAllFields" boolean NOT NULL,
    "CanDeleteTask" boolean NOT NULL,
    "CanReviewTask" boolean NOT NULL,
    CONSTRAINT "PK_BoardPermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BoardPermissions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_BoardPermissions_UserId_TeamName" ON "BoardPermissions" ("UserId", "TeamName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260218094534_AddBoardPermissions', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskCustomFields" ADD "DropdownOptions" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219050715_AddDropdownOptionsToCustomFields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219055005_AddIsDeletedToUsers', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "NumericId" integer NOT NULL DEFAULT 0;


DO $$
DECLARE
    admin_role_id TEXT;
    counter INT := 100;
    rec RECORD;
BEGIN
    -- Find the Admin role id
    SELECT "Id" INTO admin_role_id
    FROM "AspNetRoles"
    WHERE "Name" = 'Admin'
    LIMIT 1;

    -- Admin user first gets 100
    IF admin_role_id IS NOT NULL THEN
        UPDATE "AspNetUsers" u
        SET "NumericId" = 100
        FROM "AspNetUserRoles" ur
        WHERE ur."UserId" = u."Id"
          AND ur."RoleId" = admin_role_id;
    END IF;

    -- All remaining users (non-admin) get 101, 102, … ordered to be deterministic
    FOR rec IN
        SELECT u."Id"
        FROM "AspNetUsers" u
        WHERE u."NumericId" = 0
        ORDER BY u."UserName" ASC
    LOOP
        counter := counter + 1;
        UPDATE "AspNetUsers"
        SET "NumericId" = counter
        WHERE "Id" = rec."Id";
    END LOOP;
END $$;


CREATE UNIQUE INDEX "IX_AspNetUsers_NumericId" ON "AspNetUsers" ("NumericId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219111020_AddNumericUserId', '10.0.1');

COMMIT;

START TRANSACTION;

DO $$
DECLARE
    CONSTRAINT_REC RECORD;
BEGIN
    -- 1. Create mapping
    CREATE TEMP TABLE id_mapping AS
    SELECT "Id" as old_id, "NumericId"::TEXT as new_id
    FROM "AspNetUsers";

    -- 2. Drop all Foreign Keys pointing to AspNetUsers
    FOR CONSTRAINT_REC IN 
        SELECT 
            conname, 
            conrelid::regclass::text as tablename
        FROM pg_constraint 
        WHERE confrelid = '"AspNetUsers"'::regclass
    LOOP
        EXECUTE 'ALTER TABLE ' || CONSTRAINT_REC.tablename || ' DROP CONSTRAINT "' || CONSTRAINT_REC.conname || '"';
    END LOOP;

    -- 3. Update AspNetUsers itself (including self-references)
    UPDATE "AspNetUsers" u SET "Id" = m.new_id FROM id_mapping m WHERE u."Id" = m.old_id;
    UPDATE "AspNetUsers" u SET "ParentUserId" = m.new_id FROM id_mapping m WHERE u."ParentUserId" = m.old_id;
    UPDATE "AspNetUsers" u SET "ManagerId" = m.new_id FROM id_mapping m WHERE u."ManagerId" = m.old_id;

    -- 4. Update Identity Tables
    UPDATE "AspNetUserRoles" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;
    UPDATE "AspNetUserClaims" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;
    UPDATE "AspNetUserLogins" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;
    UPDATE "AspNetUserTokens" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;

    -- 5. Update Application Tables
    UPDATE "AssignedTasks" t SET "AssignedById" = m.new_id FROM id_mapping m WHERE t."AssignedById" = m.old_id;
    UPDATE "AssignedTasks" t SET "AssignedToId" = m.new_id FROM id_mapping m WHERE t."AssignedToId" = m.old_id;
    
    UPDATE "BoardPermissions" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;
    
    UPDATE "DailyReports" t SET "ApplicationUserId" = m.new_id FROM id_mapping m WHERE t."ApplicationUserId" = m.old_id;
    
    UPDATE "EmailLogs" t SET "SentByUserId" = m.new_id FROM id_mapping m WHERE t."SentByUserId" = m.old_id;
    
    UPDATE "Epics" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    UPDATE "Features" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    UPDATE "Projects" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    UPDATE "Stories" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    
    UPDATE "TaskCustomFields" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    
    UPDATE "TaskHistories" t SET "ChangedByUserId" = m.new_id FROM id_mapping m WHERE t."ChangedByUserId" = m.old_id;
    
    UPDATE "TaskItems" t SET "AssignedToUserId" = m.new_id FROM id_mapping m WHERE t."AssignedToUserId" = m.old_id;
    UPDATE "TaskItems" t SET "AssignedByUserId" = m.new_id FROM id_mapping m WHERE t."AssignedByUserId" = m.old_id;
    UPDATE "TaskItems" t SET "CreatedByUserId" = m.new_id FROM id_mapping m WHERE t."CreatedByUserId" = m.old_id;
    UPDATE "TaskItems" t SET "ReviewedByUserId" = m.new_id FROM id_mapping m WHERE t."ReviewedByUserId" = m.old_id;
    UPDATE "TaskItems" t SET "CompletedByUserId" = m.new_id FROM id_mapping m WHERE t."CompletedByUserId" = m.old_id;
    
    UPDATE "UserTeams" t SET "UserId" = m.new_id FROM id_mapping m WHERE t."UserId" = m.old_id;

    -- 5.5 Cleanup Orphans (Records pointing to non-existent users)
    -- This prevents FK violations when re-adding constraints if old data was inconsistent
    DELETE FROM "AspNetUserRoles" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    DELETE FROM "AspNetUserClaims" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    DELETE FROM "AspNetUserLogins" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    DELETE FROM "AspNetUserTokens" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");

    DELETE FROM "AssignedTasks" WHERE "AssignedById" NOT IN (SELECT "Id" FROM "AspNetUsers");
    DELETE FROM "AssignedTasks" WHERE "AssignedToId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    DELETE FROM "BoardPermissions" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    DELETE FROM "DailyReports" WHERE "ApplicationUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    UPDATE "EmailLogs" SET "SentByUserId" = NULL WHERE "SentByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    UPDATE "Epics" SET "CreatedByUserId" = NULL WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    UPDATE "Features" SET "CreatedByUserId" = NULL WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    UPDATE "Projects" SET "CreatedByUserId" = NULL WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers") OR "CreatedByUserId" IS NULL; -- Projects usually required, but we'll try to be safe
    UPDATE "Stories" SET "CreatedByUserId" = NULL WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    UPDATE "TaskCustomFields" SET "CreatedByUserId" = NULL WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    DELETE FROM "TaskHistories" WHERE "ChangedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers") AND "ChangedByUserId" IS NOT NULL;
    
    DELETE FROM "TaskItems" WHERE "AssignedToUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    UPDATE "TaskItems" SET "AssignedByUserId" = NULL WHERE "AssignedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    DELETE FROM "TaskItems" WHERE "CreatedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    UPDATE "TaskItems" SET "ReviewedByUserId" = NULL WHERE "ReviewedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    UPDATE "TaskItems" SET "CompletedByUserId" = NULL WHERE "CompletedByUserId" NOT IN (SELECT "Id" FROM "AspNetUsers");
    
    DELETE FROM "UserTeams" WHERE "UserId" NOT IN (SELECT "Id" FROM "AspNetUsers");

    -- 6. Re-add Foreign Keys (Standard EF Naming)
    ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_AspNetUsers_ParentUserId" FOREIGN KEY ("ParentUserId") REFERENCES "AspNetUsers"("Id");
    ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_AspNetUsers_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers"("Id");
    
    ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;

    ALTER TABLE "AssignedTasks" ADD CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedById" FOREIGN KEY ("AssignedById") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    ALTER TABLE "AssignedTasks" ADD CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    
    ALTER TABLE "BoardPermissions" ADD CONSTRAINT "FK_BoardPermissions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    
    ALTER TABLE "DailyReports" ADD CONSTRAINT "FK_DailyReports_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    
    ALTER TABLE "EmailLogs" ADD CONSTRAINT "FK_EmailLogs_AspNetUsers_SentByUserId" FOREIGN KEY ("SentByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
    
    ALTER TABLE "Epics" ADD CONSTRAINT "FK_Epics_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id");
    ALTER TABLE "Features" ADD CONSTRAINT "FK_Features_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id");
    ALTER TABLE "Projects" ADD CONSTRAINT "FK_Projects_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    ALTER TABLE "Stories" ADD CONSTRAINT "FK_Stories_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id");
    
    ALTER TABLE "TaskCustomFields" ADD CONSTRAINT "FK_TaskCustomFields_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id");
    
    ALTER TABLE "TaskHistories" ADD CONSTRAINT "FK_TaskHistories_AspNetUsers_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    
    ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_CompletedByUserId" FOREIGN KEY ("CompletedByUserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
    
    ALTER TABLE "UserTeams" ADD CONSTRAINT "FK_UserTeams_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;

END $$;


ALTER TABLE "AssignedTasks" DROP CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedById";

ALTER TABLE "TaskItems" DROP CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedByUserId";

ALTER TABLE "TaskItems" DROP CONSTRAINT "FK_TaskItems_AspNetUsers_CreatedByUserId";

DROP INDEX "IX_AspNetUsers_NumericId";

ALTER TABLE "AspNetUsers" DROP COLUMN "NumericId";

ALTER TABLE "AssignedTasks" ADD CONSTRAINT "FK_AssignedTasks_AspNetUsers_AssignedById" FOREIGN KEY ("AssignedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219113800_ReplaceGuidIdsWithNumericIds', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" DROP COLUMN "IsDeleted";

ALTER TABLE "Teams" ADD "IsDueDateVisible" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Teams" ADD "IsPriorityVisible" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "TaskItems" ADD "DueDate" timestamp with time zone;

ALTER TABLE "TaskCustomFields" ADD "TeamName" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219161520_AddTeamSpecificCustomFieldsAndDueDate', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Teams" ADD "IsDescriptionVisible" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Teams" ADD "IsTitleVisible" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220060137_AddVisibleColumnsToTeams', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "ExcelImportLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NOT NULL,
    "TeamName" text NOT NULL,
    "ColumnId" integer NOT NULL,
    "ColumnName" text NOT NULL,
    "TotalRows" integer NOT NULL,
    "SuccessCount" integer NOT NULL,
    "ErrorCount" integer NOT NULL,
    "Status" text NOT NULL,
    "ErrorDetails" text,
    "ImportedByUserId" text NOT NULL,
    "ImportedAt" timestamp with time zone NOT NULL,
    "DurationMs" bigint,
    CONSTRAINT "PK_ExcelImportLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExcelImportLogs_AspNetUsers_ImportedByUserId" FOREIGN KEY ("ImportedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ExcelImportLogs_ImportedByUserId" ON "ExcelImportLogs" ("ImportedByUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220064104_AddExcelImportLog', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "BoardPermissions" ADD "CanImportExcel" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220074057_AddCanImportExcelPermission', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "BoardPermissions" ADD "CanAssignTask" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220114044_AddCanAssignTaskPermission', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskFieldValues" ADD "FileName" text;

ALTER TABLE "TaskFieldValues" ADD "ImageData" bytea;

ALTER TABLE "TaskFieldValues" ADD "ImageMimeType" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225091727_AddImageDataToCustomFields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Stories" ADD "AssignedToUserId" text;

ALTER TABLE "Features" ADD "AssignedToUserId" text;

CREATE TABLE "ProjectMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "UserId" text NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL,
    "ProjectRole" text,
    CONSTRAINT "PK_ProjectMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectMembers_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Stories_AssignedToUserId" ON "Stories" ("AssignedToUserId");

CREATE INDEX "IX_Features_AssignedToUserId" ON "Features" ("AssignedToUserId");

CREATE INDEX "IX_ProjectMembers_ProjectId" ON "ProjectMembers" ("ProjectId");

CREATE INDEX "IX_ProjectMembers_UserId" ON "ProjectMembers" ("UserId");

ALTER TABLE "Features" ADD CONSTRAINT "FK_Features_AspNetUsers_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Stories" ADD CONSTRAINT "FK_Stories_AspNetUsers_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225115840_AddHierarchicalAssignments', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "BoardPermissions" ADD "AllowedTransitionsJson" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227111251_AddAllowedTransitionsToBoardPermissionFinal', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "BoardPermissions" ADD "MoveRequestsJson" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227130714_AddMoveRequestsToBoardPermissionV2', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "ColumnPermissions" ADD "CanClearTasks" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228070913_AddCanClearTasksOnly', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260301161311_FixMissingProperties', '10.0.1');

COMMIT;

